#!/usr/bin/env python

import sys
import PyPDF2

input = open(sys.argv[1], 'rb')
overlay = open(sys.argv[2], 'rb')
output = open(sys.argv[3], 'wb')

inputReader = PyPDF2.PdfFileReader(input)
overlayReader = PyPDF2.PdfFileReader(overlay)
outputWriter = PyPDF2.PdfFileWriter()

overlayPage = overlayReader.getPage(0)

for pageNum in range(inputReader.numPages):
    pageObj = inputReader.getPage(pageNum)
    if pageNum == 0:
        pageObj.mergePage(overlayPage)
    outputWriter.addPage(pageObj)

outputWriter.write(output)

input.close()
overlay.close()
output.close()


CUPS_JOB="$1"
CUPS_USER="$2"
CUPS_TITLE="$3"
CUPS_NUMCOPIES="$4"
CUPS_OPTIONS="$5"
CUPS_FILENAME="$6"
