#!/usr/bin/env python3

import sys
import PyPDF2

cups_job = sys.argv[1]
cups_user = sys.argv[2]
cups_title = sys.argv[3]
cups_numcopies = sys.argv[4]
cups_options = sys.argv[5]
cups_filename = sys.argv[6]
output_filename = sys.argv[7]

input = open(cups_filename, 'rb')
overlay = open('/bpc/PDFs/overlay.pdf', 'rb')
output = open(output_filename, 'wb')

inputReader = PyPDF2.PdfFileReader(input)
overlayReader = PyPDF2.PdfFileReader(overlay)
outputWriter = PyPDF2.PdfFileWriter()

overlayPage = overlayReader.getPage(0)

for pageNum in range(inputReader.numPages):
    pageObj = inputReader.getPage(pageNum)
    if pageNum == 0:
        pageObj.mergePage(overlayPage)
    outputWriter.addPage(pageObj)

outputWriter.write(output)

input.close()
overlay.close()
output.close()

